version: 0.2

env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "{{s3_bucket_url}}"
    BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing source NPM dependencies...
      - npm install --legacy-peer-deps
      - npm install -g @angular/cli
  # pre_build:
  #   commands:
  #     - npm cache clean --force
  #     - rm -rf node_modules dist
  build:
    commands:
      - echo Build started on `date`
      - ng build --configuration production
  # post_build:
  #    commands:
  #     - aws s3 cp dist s3://taskmanagerwebapp --recursive
  #     - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
