version: 0.2

env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "{{s3_bucket_url}}"
    BUILD_FOLDER: "dist"
phases:
  # pre_build:
  #   commands:
  #     - npm cache clean --force
  #     - rm -rf node_modules dist
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing source NPM dependencies...
      - npm install -g @angular/cli
      - npm install --legacy-peer-deps
  build:
    commands:
      - echo Build started on `date`
      - ng build --configuration=production
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 cp s3://taskmanagerwebapp --region eu-west-2 /var/www/html --recursive

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  discard-paths: yes
